export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';

export const FETCH_PRODUCTS_DETAILS_SUCCESS = 'FETCH_PRODUCTS_DETAILS_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_FAIL = 'FETCH_PRODUCTS_DETAILS_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
